<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/school/admin/css/table.css"); ?>
<table id="CSS_Table">
    <tr>
        <th> Gallery ID        </th>
        <th> Gallery Name    </th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    <?php foreach ($this->result as $result): ?>

        <tr>
            <td><?php echo $result['gallery_id']; ?></td>
            <td><?php echo $result['gallery_name']; ?></td>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'gallery', 'action' => 'edit', 'id' => $result['gallery_id'])); ?>">Edit </a>
            </td>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'gallery', 'action' => 'delete', 'id' => $result['gallery_id'])); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
