<html>
    <head>
        <title>Login of School Management System</title>
        <?php echo $this->headLink(); ?>
    </head>
    <body>
        <div class="flash-messages">
            <?php
            $flashMessenger = $this->flashMessages();
            print $flashMessenger->getMessages();
            ?>
        </div>
        <div id="container">
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>