<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false">
</script>

<script>
    var latitude = "<?php echo $this->config->school->latitude; ?>"
    var longitude = "<?php echo $this->config->school->longitude; ?>"
    var myCenter=new google.maps.LatLng(latitude,longitude);
    var marker;

    function initialize()
    {
        var mapProp = {
            center:myCenter,
            zoom:<?php echo $this->config->school->zoom; ?>,
            mapTypeId:google.maps.MapTypeId.ROADMAP
        };

        var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

        marker=new google.maps.Marker({
            position:myCenter,
            animation:google.maps.Animation.BOUNCE
        });

        marker.setMap(map);
    }

    google.maps.event.addDomListener(window, 'load', initialize);
</script>
<div id="googleMap" style="width:650px;height:500px;"></div>
