<div id="dashboard">
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/examtype/add'; ?>">Add Exam Type</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/result/search'; ?>"> Add Result</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/result/'; ?>"> Search Result</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/student/list'; ?>">Students</a></div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/staff/list'; ?>">Staff</a></div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/subject/list'; ?>">Subjects</a></div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/image/list'; ?>">Image</a></div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/news/list'; ?>">News feed</a></div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/gallery/list'; ?>">Gallery</a></div>
</div>